name: DevSecOps CI

on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v3

  # Stage 2 (Parallel)
  checkov:
    name: Checkov Scan
    needs: gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Running Checkov"

  trivy-fs:
    name: Trivy Filesystem Scan
    needs: gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Running Trivy FS"

  lint:
    name: Lint
    needs: gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Running Linter"

  tests:
    name: Unit Tests
    needs: gitleaks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Running Tests"

  # Stage 3
  sonarqube:
    name: SonarQube Analysis
    needs:
      - checkov
      - trivy-fs
      - lint
      - tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "Running SonarQube"
